# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majority', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.PositiveSmallIntegerField(choices=[(0, 'A rejeter'), (1, 'Insuffisant'), (2, 'Passable'), (3, 'Assez Bien'), (4, 'Bien'), (5, 'Très bien'), (6, 'Excellent')])),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='option',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majority.Vote'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majority.Option'),
        ),
    ]
