# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majority', '0002_auto_20170512_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='majority.Option'),
        ),
        migrations.AlterField(
            model_name='option',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='majority.Vote'),
        ),
    ]
